spring:
  config:
    activate:
      on-profile: local # 환경 이름 설정

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(SM2SX86yFuXBR2xw8P0EfhmNTiXLP29JZWVKpfJv5zBGVknBVfRNYNR0VBoP9iL3)
    username: ENC(AGh9edGe23clEkN1lqwdN40OOwfuJRk0)
    password: ENC(HwvBK09P6X2Nryj0IEAnZw==)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect

  devtools:
    remote:
      restart:
        enabled: true

  jackson:
    parser:
      allow-unquoted-control-chars: true

  security:
    user:
      name: user
      password: 1234

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#API Document
springdoc:
  swagger-ui:
    enabled: true
    path: studyLog4uAPI.html
  paths-to-match:
    - /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

app:
  oauth2:
    authorizedRedirectUris: http://localhost:3000/oauth2/redirect
  client:
    url: http://localhost:3000
  slack:
    token: ENC(YRQMci9lJSad4DQ3QrpfEjhcVdMuJmoO+n1/Lvcvd47Q/Cq+X0hEoaq3f6u9KIqwj+pHJnXyfu6VqxyHJXCoC+tXbLIyFMAC)

#app:
#  auth:
#    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
#    tokenExpiry: 1800000
#    refreshTokenExpiry: 604800000
#  oauth2:
#    authorizedRedirectUris:
#      - http://localhost:3000/oauth2/redirect