# Local server
server:
  port: 9091

spring:
  config:
    activate:
      on-profile: local # 환경 이름 설정

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(v+lq+C25uMuPxdEg6vxydI1CGIjUsGA9O3LEmIeYggN5uT+9sZRtHeBpEo9aeTee2RBClCBlOq8CxsO0s+J26V+50HGhSwGDmuf1DeZNbChaAvW2zwGiLQlnR4TGzvn30w/p5sdZj8k=)
    username: ENC(f3sdCTIXOb1crVjmI0tmZA==)
    password: ENC(5sBpAu95kyyPUZ4ThXHYhjfVOL2swK8h)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect

  devtools:
    remote:
      restart:
        enabled: true

  jackson:
    parser:
      allow-unquoted-control-chars: true

#API Document
springdoc:
  swagger-ui:
    enabled: true
    path: studyLog4uAPI.html
  paths-to-match:
    - /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

app:
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect