sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ENC(OvplBtCjkTU/whMpok/kj0Mm304kDY8o5NxJJwY97Wev6ztDoZ87tHVkLjT8Mfea1BVgJY07PP3Or31KgF+uh92C1J3js0WiiK1HdOWYWyhiLOE+bF0Q6Q==)
    client-secret: ENC(j2dpXIZbcTXE9VcrejFueRpPGPlIz0TsCIJwoH/9skOGZqvwyh5PPBDhEE2pBHJ+)
    #redirect-uri: http://localhost:9091/oauth2/callback/google #local
    redirect-uri: http://0.0.0.0:9091/oauth2/callback/google
    token-base-url: https://oauth2.googleapis.com/token
    userinfo-request-url: https://www.googleapis.com/oauth2/v1/userinfo
    user-password: ENC(T8vIJalbw6Rfl4rQAHWShw==)

jwt:
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다. 아래 값은 Secret Key 를 Base64 로 인코딩한 값임.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  # 토큰 만료 시간 지정
  token-validity-in-seconds: 86400