spring:
  config:
    activate:
      on-profile: prod # 환경 이름 설정

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(U8ZPcC4nPVIJh/OvCZlnGbdeaxRdKZl2hTpfd+nQCXBvOsHqck/k9At6lLwqxUY1W2Kce7w2WN6g2rVQEIeb1XbHi+YPVZF0LQVhVF3tAf4plA+s6NK9D8KvvEP+2kOolEOC0Z94Qy4=)
    username: ENC(f3sdCTIXOb1crVjmI0tmZA==)
    password: ENC(5sBpAu95kyyPUZ4ThXHYhjfVOL2swK8h)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect

  devtools:
    remote:
      restart:
        enabled: true

  jackson:
    parser:
      allow-unquoted-control-chars: true

  security:
    user:
      name: user
      password: 1234

#API Document
springdoc:
  swagger-ui:
    enabled: true
    path: studyLog4uAPI.html
  paths-to-match:
    - /api/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

app:
  oauth2:
    authorizedRedirectUris: http://www.studylog4u.xyz/oauth2/redirect
  client:
    url: http://www.studylog4u.xyz
  slack:
    token: ENC(YRQMci9lJSad4DQ3QrpfEjhcVdMuJmoO+n1/Lvcvd47Q/Cq+X0hEoaq3f6u9KIqwj+pHJnXyfu6VqxyHJXCoC+tXbLIyFMAC)