sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client-id: ENC(OvplBtCjkTU/whMpok/kj0Mm304kDY8o5NxJJwY97Wev6ztDoZ87tHVkLjT8Mfea1BVgJY07PP3Or31KgF+uh92C1J3js0WiiK1HdOWYWyhiLOE+bF0Q6Q==)
    client-secret: ENC(j2dpXIZbcTXE9VcrejFueRpPGPlIz0TsCIJwoH/9skOGZqvwyh5PPBDhEE2pBHJ+)
    #redirect-uri: http://localhost:9091/oauth2/callback/google #local
    redirect-uri: http://studylog4u.xyz:9091/oauth2/callback/google
    token-base-url: https://oauth2.googleapis.com/token
    userinfo-request-url: https://www.googleapis.com/oauth2/v1/userinfo
    user-password: ENC(T8vIJalbw6Rfl4rQAHWShw==)

jwt:
  secret: ENC(9sWv46HOLHtjnIndfP/jxKDiRubHQId+id3ttMoEqz27FzB+akdhgF+ZxBH+yGJOStJzeaQ9RDI3W2B9o8x0lryOkM2VRfc2JOowjhKfkQZSuudMEC38nR4f/xBhQKW8Ct5baQJVk36MnoEqEnoQvsQmXPFadPU9cp/MJ6IjMds8Qjom46zVpyx4PljQnVvW)
  token-validity-in-seconds: 86400